/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardUsersRouteImport } from './routes/dashboard/users'
import { Route as DashboardUserManualRouteImport } from './routes/dashboard/user-manual'
import { Route as DashboardSystemDocsRouteImport } from './routes/dashboard/system-docs'
import { Route as DashboardSystemConfigRouteImport } from './routes/dashboard/system-config'
import { Route as DashboardRolePermissionsRouteImport } from './routes/dashboard/role-permissions'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardMenuManagementRouteImport } from './routes/dashboard/menu-management'
import { Route as DashboardLookupsRouteImport } from './routes/dashboard/lookups'
import { Route as DashboardIssueReportsRouteImport } from './routes/dashboard/issue-reports'
import { Route as DashboardFeatureRequestsRouteImport } from './routes/dashboard/feature-requests'
import { Route as DashboardErrorLogsRouteImport } from './routes/dashboard/error-logs'
import { Route as DashboardEipRouteImport } from './routes/dashboard/eip'
import { Route as DashboardDevTodosRouteImport } from './routes/dashboard/dev-todos'
import { Route as DashboardDevHistoryRouteImport } from './routes/dashboard/dev-history'
import { Route as DashboardAuditLogsRouteImport } from './routes/dashboard/audit-logs'
import { Route as DashboardAssistantIntentRouteImport } from './routes/dashboard/assistant-intent'
import { Route as DashboardActivityLogsRouteImport } from './routes/dashboard/activity-logs'
import { Route as DashboardEipTasksRouteImport } from './routes/dashboard/eip/tasks'
import { Route as DashboardEipReportsRouteImport } from './routes/dashboard/eip/reports'
import { Route as DashboardEipRecurringRouteImport } from './routes/dashboard/eip/recurring'
import { Route as DashboardEipQuickReportsRouteImport } from './routes/dashboard/eip/quick-reports'
import { Route as DashboardEipProjectsRouteImport } from './routes/dashboard/eip/projects'
import { Route as DashboardEipMyTasksRouteImport } from './routes/dashboard/eip/my-tasks'
import { Route as DashboardEipMembersRouteImport } from './routes/dashboard/eip/members'
import { Route as DashboardEipMeetingsRouteImport } from './routes/dashboard/eip/meetings'
import { Route as DashboardEipFeatureRequestsRouteImport } from './routes/dashboard/eip/feature-requests'
import { Route as DashboardEipDocumentsRouteImport } from './routes/dashboard/eip/documents'
import { Route as DashboardEipChangelogRouteImport } from './routes/dashboard/eip/changelog'
import { Route as DashboardEipCalendarRouteImport } from './routes/dashboard/eip/calendar'
import { Route as DashboardEipAssistantRouteImport } from './routes/dashboard/eip/assistant'
import { Route as DashboardEipAnnouncementsRouteImport } from './routes/dashboard/eip/announcements'
import { Route as DashboardEipProjectsIndexRouteImport } from './routes/dashboard/eip/projects.index'
import { Route as DashboardEipMeetingsIndexRouteImport } from './routes/dashboard/eip/meetings.index'
import { Route as DashboardEipProjectsIdRouteImport } from './routes/dashboard/eip/projects.$id'
import { Route as DashboardEipMeetingsIdRouteImport } from './routes/dashboard/eip/meetings.$id'
import { Route as DashboardEipFeatureRequestsNewRouteImport } from './routes/dashboard/eip/feature-requests.new'
import { Route as DashboardEipFeatureRequestsIdRouteImport } from './routes/dashboard/eip/feature-requests.$id'
import { Route as DashboardEipFeatureRequestsIdEditRouteImport } from './routes/dashboard/eip/feature-requests.$id.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUserManualRoute = DashboardUserManualRouteImport.update({
  id: '/user-manual',
  path: '/user-manual',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSystemDocsRoute = DashboardSystemDocsRouteImport.update({
  id: '/system-docs',
  path: '/system-docs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSystemConfigRoute = DashboardSystemConfigRouteImport.update({
  id: '/system-config',
  path: '/system-config',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRolePermissionsRoute =
  DashboardRolePermissionsRouteImport.update({
    id: '/role-permissions',
    path: '/role-permissions',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMenuManagementRoute = DashboardMenuManagementRouteImport.update({
  id: '/menu-management',
  path: '/menu-management',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLookupsRoute = DashboardLookupsRouteImport.update({
  id: '/lookups',
  path: '/lookups',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIssueReportsRoute = DashboardIssueReportsRouteImport.update({
  id: '/issue-reports',
  path: '/issue-reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFeatureRequestsRoute =
  DashboardFeatureRequestsRouteImport.update({
    id: '/feature-requests',
    path: '/feature-requests',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardErrorLogsRoute = DashboardErrorLogsRouteImport.update({
  id: '/error-logs',
  path: '/error-logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEipRoute = DashboardEipRouteImport.update({
  id: '/eip',
  path: '/eip',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDevTodosRoute = DashboardDevTodosRouteImport.update({
  id: '/dev-todos',
  path: '/dev-todos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDevHistoryRoute = DashboardDevHistoryRouteImport.update({
  id: '/dev-history',
  path: '/dev-history',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuditLogsRoute = DashboardAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAssistantIntentRoute =
  DashboardAssistantIntentRouteImport.update({
    id: '/assistant-intent',
    path: '/assistant-intent',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardActivityLogsRoute = DashboardActivityLogsRouteImport.update({
  id: '/activity-logs',
  path: '/activity-logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEipTasksRoute = DashboardEipTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => DashboardEipRoute,
} as any)
const DashboardEipReportsRoute = DashboardEipReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardEipRoute,
} as any)
const DashboardEipRecurringRoute = DashboardEipRecurringRouteImport.update({
  id: '/recurring',
  path: '/recurring',
  getParentRoute: () => DashboardEipRoute,
} as any)
const DashboardEipQuickReportsRoute =
  DashboardEipQuickReportsRouteImport.update({
    id: '/quick-reports',
    path: '/quick-reports',
    getParentRoute: () => DashboardEipRoute,
  } as any)
const DashboardEipProjectsRoute = DashboardEipProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardEipRoute,
} as any)
const DashboardEipMyTasksRoute = DashboardEipMyTasksRouteImport.update({
  id: '/my-tasks',
  path: '/my-tasks',
  getParentRoute: () => DashboardEipRoute,
} as any)
const DashboardEipMembersRoute = DashboardEipMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => DashboardEipRoute,
} as any)
const DashboardEipMeetingsRoute = DashboardEipMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => DashboardEipRoute,
} as any)
const DashboardEipFeatureRequestsRoute =
  DashboardEipFeatureRequestsRouteImport.update({
    id: '/feature-requests',
    path: '/feature-requests',
    getParentRoute: () => DashboardEipRoute,
  } as any)
const DashboardEipDocumentsRoute = DashboardEipDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => DashboardEipRoute,
} as any)
const DashboardEipChangelogRoute = DashboardEipChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => DashboardEipRoute,
} as any)
const DashboardEipCalendarRoute = DashboardEipCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DashboardEipRoute,
} as any)
const DashboardEipAssistantRoute = DashboardEipAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => DashboardEipRoute,
} as any)
const DashboardEipAnnouncementsRoute =
  DashboardEipAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => DashboardEipRoute,
  } as any)
const DashboardEipProjectsIndexRoute =
  DashboardEipProjectsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardEipProjectsRoute,
  } as any)
const DashboardEipMeetingsIndexRoute =
  DashboardEipMeetingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardEipMeetingsRoute,
  } as any)
const DashboardEipProjectsIdRoute = DashboardEipProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardEipProjectsRoute,
} as any)
const DashboardEipMeetingsIdRoute = DashboardEipMeetingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardEipMeetingsRoute,
} as any)
const DashboardEipFeatureRequestsNewRoute =
  DashboardEipFeatureRequestsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => DashboardEipFeatureRequestsRoute,
  } as any)
const DashboardEipFeatureRequestsIdRoute =
  DashboardEipFeatureRequestsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => DashboardEipFeatureRequestsRoute,
  } as any)
const DashboardEipFeatureRequestsIdEditRoute =
  DashboardEipFeatureRequestsIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => DashboardEipFeatureRequestsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/activity-logs': typeof DashboardActivityLogsRoute
  '/dashboard/assistant-intent': typeof DashboardAssistantIntentRoute
  '/dashboard/audit-logs': typeof DashboardAuditLogsRoute
  '/dashboard/dev-history': typeof DashboardDevHistoryRoute
  '/dashboard/dev-todos': typeof DashboardDevTodosRoute
  '/dashboard/eip': typeof DashboardEipRouteWithChildren
  '/dashboard/error-logs': typeof DashboardErrorLogsRoute
  '/dashboard/feature-requests': typeof DashboardFeatureRequestsRoute
  '/dashboard/issue-reports': typeof DashboardIssueReportsRoute
  '/dashboard/lookups': typeof DashboardLookupsRoute
  '/dashboard/menu-management': typeof DashboardMenuManagementRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/role-permissions': typeof DashboardRolePermissionsRoute
  '/dashboard/system-config': typeof DashboardSystemConfigRoute
  '/dashboard/system-docs': typeof DashboardSystemDocsRoute
  '/dashboard/user-manual': typeof DashboardUserManualRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/eip/announcements': typeof DashboardEipAnnouncementsRoute
  '/dashboard/eip/assistant': typeof DashboardEipAssistantRoute
  '/dashboard/eip/calendar': typeof DashboardEipCalendarRoute
  '/dashboard/eip/changelog': typeof DashboardEipChangelogRoute
  '/dashboard/eip/documents': typeof DashboardEipDocumentsRoute
  '/dashboard/eip/feature-requests': typeof DashboardEipFeatureRequestsRouteWithChildren
  '/dashboard/eip/meetings': typeof DashboardEipMeetingsRouteWithChildren
  '/dashboard/eip/members': typeof DashboardEipMembersRoute
  '/dashboard/eip/my-tasks': typeof DashboardEipMyTasksRoute
  '/dashboard/eip/projects': typeof DashboardEipProjectsRouteWithChildren
  '/dashboard/eip/quick-reports': typeof DashboardEipQuickReportsRoute
  '/dashboard/eip/recurring': typeof DashboardEipRecurringRoute
  '/dashboard/eip/reports': typeof DashboardEipReportsRoute
  '/dashboard/eip/tasks': typeof DashboardEipTasksRoute
  '/dashboard/eip/feature-requests/$id': typeof DashboardEipFeatureRequestsIdRouteWithChildren
  '/dashboard/eip/feature-requests/new': typeof DashboardEipFeatureRequestsNewRoute
  '/dashboard/eip/meetings/$id': typeof DashboardEipMeetingsIdRoute
  '/dashboard/eip/projects/$id': typeof DashboardEipProjectsIdRoute
  '/dashboard/eip/meetings/': typeof DashboardEipMeetingsIndexRoute
  '/dashboard/eip/projects/': typeof DashboardEipProjectsIndexRoute
  '/dashboard/eip/feature-requests/$id/edit': typeof DashboardEipFeatureRequestsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/activity-logs': typeof DashboardActivityLogsRoute
  '/dashboard/assistant-intent': typeof DashboardAssistantIntentRoute
  '/dashboard/audit-logs': typeof DashboardAuditLogsRoute
  '/dashboard/dev-history': typeof DashboardDevHistoryRoute
  '/dashboard/dev-todos': typeof DashboardDevTodosRoute
  '/dashboard/eip': typeof DashboardEipRouteWithChildren
  '/dashboard/error-logs': typeof DashboardErrorLogsRoute
  '/dashboard/feature-requests': typeof DashboardFeatureRequestsRoute
  '/dashboard/issue-reports': typeof DashboardIssueReportsRoute
  '/dashboard/lookups': typeof DashboardLookupsRoute
  '/dashboard/menu-management': typeof DashboardMenuManagementRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/role-permissions': typeof DashboardRolePermissionsRoute
  '/dashboard/system-config': typeof DashboardSystemConfigRoute
  '/dashboard/system-docs': typeof DashboardSystemDocsRoute
  '/dashboard/user-manual': typeof DashboardUserManualRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/eip/announcements': typeof DashboardEipAnnouncementsRoute
  '/dashboard/eip/assistant': typeof DashboardEipAssistantRoute
  '/dashboard/eip/calendar': typeof DashboardEipCalendarRoute
  '/dashboard/eip/changelog': typeof DashboardEipChangelogRoute
  '/dashboard/eip/documents': typeof DashboardEipDocumentsRoute
  '/dashboard/eip/feature-requests': typeof DashboardEipFeatureRequestsRouteWithChildren
  '/dashboard/eip/members': typeof DashboardEipMembersRoute
  '/dashboard/eip/my-tasks': typeof DashboardEipMyTasksRoute
  '/dashboard/eip/quick-reports': typeof DashboardEipQuickReportsRoute
  '/dashboard/eip/recurring': typeof DashboardEipRecurringRoute
  '/dashboard/eip/reports': typeof DashboardEipReportsRoute
  '/dashboard/eip/tasks': typeof DashboardEipTasksRoute
  '/dashboard/eip/feature-requests/$id': typeof DashboardEipFeatureRequestsIdRouteWithChildren
  '/dashboard/eip/feature-requests/new': typeof DashboardEipFeatureRequestsNewRoute
  '/dashboard/eip/meetings/$id': typeof DashboardEipMeetingsIdRoute
  '/dashboard/eip/projects/$id': typeof DashboardEipProjectsIdRoute
  '/dashboard/eip/meetings': typeof DashboardEipMeetingsIndexRoute
  '/dashboard/eip/projects': typeof DashboardEipProjectsIndexRoute
  '/dashboard/eip/feature-requests/$id/edit': typeof DashboardEipFeatureRequestsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/activity-logs': typeof DashboardActivityLogsRoute
  '/dashboard/assistant-intent': typeof DashboardAssistantIntentRoute
  '/dashboard/audit-logs': typeof DashboardAuditLogsRoute
  '/dashboard/dev-history': typeof DashboardDevHistoryRoute
  '/dashboard/dev-todos': typeof DashboardDevTodosRoute
  '/dashboard/eip': typeof DashboardEipRouteWithChildren
  '/dashboard/error-logs': typeof DashboardErrorLogsRoute
  '/dashboard/feature-requests': typeof DashboardFeatureRequestsRoute
  '/dashboard/issue-reports': typeof DashboardIssueReportsRoute
  '/dashboard/lookups': typeof DashboardLookupsRoute
  '/dashboard/menu-management': typeof DashboardMenuManagementRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/role-permissions': typeof DashboardRolePermissionsRoute
  '/dashboard/system-config': typeof DashboardSystemConfigRoute
  '/dashboard/system-docs': typeof DashboardSystemDocsRoute
  '/dashboard/user-manual': typeof DashboardUserManualRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/eip/announcements': typeof DashboardEipAnnouncementsRoute
  '/dashboard/eip/assistant': typeof DashboardEipAssistantRoute
  '/dashboard/eip/calendar': typeof DashboardEipCalendarRoute
  '/dashboard/eip/changelog': typeof DashboardEipChangelogRoute
  '/dashboard/eip/documents': typeof DashboardEipDocumentsRoute
  '/dashboard/eip/feature-requests': typeof DashboardEipFeatureRequestsRouteWithChildren
  '/dashboard/eip/meetings': typeof DashboardEipMeetingsRouteWithChildren
  '/dashboard/eip/members': typeof DashboardEipMembersRoute
  '/dashboard/eip/my-tasks': typeof DashboardEipMyTasksRoute
  '/dashboard/eip/projects': typeof DashboardEipProjectsRouteWithChildren
  '/dashboard/eip/quick-reports': typeof DashboardEipQuickReportsRoute
  '/dashboard/eip/recurring': typeof DashboardEipRecurringRoute
  '/dashboard/eip/reports': typeof DashboardEipReportsRoute
  '/dashboard/eip/tasks': typeof DashboardEipTasksRoute
  '/dashboard/eip/feature-requests/$id': typeof DashboardEipFeatureRequestsIdRouteWithChildren
  '/dashboard/eip/feature-requests/new': typeof DashboardEipFeatureRequestsNewRoute
  '/dashboard/eip/meetings/$id': typeof DashboardEipMeetingsIdRoute
  '/dashboard/eip/projects/$id': typeof DashboardEipProjectsIdRoute
  '/dashboard/eip/meetings/': typeof DashboardEipMeetingsIndexRoute
  '/dashboard/eip/projects/': typeof DashboardEipProjectsIndexRoute
  '/dashboard/eip/feature-requests/$id/edit': typeof DashboardEipFeatureRequestsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/activity-logs'
    | '/dashboard/assistant-intent'
    | '/dashboard/audit-logs'
    | '/dashboard/dev-history'
    | '/dashboard/dev-todos'
    | '/dashboard/eip'
    | '/dashboard/error-logs'
    | '/dashboard/feature-requests'
    | '/dashboard/issue-reports'
    | '/dashboard/lookups'
    | '/dashboard/menu-management'
    | '/dashboard/profile'
    | '/dashboard/role-permissions'
    | '/dashboard/system-config'
    | '/dashboard/system-docs'
    | '/dashboard/user-manual'
    | '/dashboard/users'
    | '/dashboard/'
    | '/dashboard/eip/announcements'
    | '/dashboard/eip/assistant'
    | '/dashboard/eip/calendar'
    | '/dashboard/eip/changelog'
    | '/dashboard/eip/documents'
    | '/dashboard/eip/feature-requests'
    | '/dashboard/eip/meetings'
    | '/dashboard/eip/members'
    | '/dashboard/eip/my-tasks'
    | '/dashboard/eip/projects'
    | '/dashboard/eip/quick-reports'
    | '/dashboard/eip/recurring'
    | '/dashboard/eip/reports'
    | '/dashboard/eip/tasks'
    | '/dashboard/eip/feature-requests/$id'
    | '/dashboard/eip/feature-requests/new'
    | '/dashboard/eip/meetings/$id'
    | '/dashboard/eip/projects/$id'
    | '/dashboard/eip/meetings/'
    | '/dashboard/eip/projects/'
    | '/dashboard/eip/feature-requests/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/activity-logs'
    | '/dashboard/assistant-intent'
    | '/dashboard/audit-logs'
    | '/dashboard/dev-history'
    | '/dashboard/dev-todos'
    | '/dashboard/eip'
    | '/dashboard/error-logs'
    | '/dashboard/feature-requests'
    | '/dashboard/issue-reports'
    | '/dashboard/lookups'
    | '/dashboard/menu-management'
    | '/dashboard/profile'
    | '/dashboard/role-permissions'
    | '/dashboard/system-config'
    | '/dashboard/system-docs'
    | '/dashboard/user-manual'
    | '/dashboard/users'
    | '/dashboard'
    | '/dashboard/eip/announcements'
    | '/dashboard/eip/assistant'
    | '/dashboard/eip/calendar'
    | '/dashboard/eip/changelog'
    | '/dashboard/eip/documents'
    | '/dashboard/eip/feature-requests'
    | '/dashboard/eip/members'
    | '/dashboard/eip/my-tasks'
    | '/dashboard/eip/quick-reports'
    | '/dashboard/eip/recurring'
    | '/dashboard/eip/reports'
    | '/dashboard/eip/tasks'
    | '/dashboard/eip/feature-requests/$id'
    | '/dashboard/eip/feature-requests/new'
    | '/dashboard/eip/meetings/$id'
    | '/dashboard/eip/projects/$id'
    | '/dashboard/eip/meetings'
    | '/dashboard/eip/projects'
    | '/dashboard/eip/feature-requests/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/activity-logs'
    | '/dashboard/assistant-intent'
    | '/dashboard/audit-logs'
    | '/dashboard/dev-history'
    | '/dashboard/dev-todos'
    | '/dashboard/eip'
    | '/dashboard/error-logs'
    | '/dashboard/feature-requests'
    | '/dashboard/issue-reports'
    | '/dashboard/lookups'
    | '/dashboard/menu-management'
    | '/dashboard/profile'
    | '/dashboard/role-permissions'
    | '/dashboard/system-config'
    | '/dashboard/system-docs'
    | '/dashboard/user-manual'
    | '/dashboard/users'
    | '/dashboard/'
    | '/dashboard/eip/announcements'
    | '/dashboard/eip/assistant'
    | '/dashboard/eip/calendar'
    | '/dashboard/eip/changelog'
    | '/dashboard/eip/documents'
    | '/dashboard/eip/feature-requests'
    | '/dashboard/eip/meetings'
    | '/dashboard/eip/members'
    | '/dashboard/eip/my-tasks'
    | '/dashboard/eip/projects'
    | '/dashboard/eip/quick-reports'
    | '/dashboard/eip/recurring'
    | '/dashboard/eip/reports'
    | '/dashboard/eip/tasks'
    | '/dashboard/eip/feature-requests/$id'
    | '/dashboard/eip/feature-requests/new'
    | '/dashboard/eip/meetings/$id'
    | '/dashboard/eip/projects/$id'
    | '/dashboard/eip/meetings/'
    | '/dashboard/eip/projects/'
    | '/dashboard/eip/feature-requests/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/user-manual': {
      id: '/dashboard/user-manual'
      path: '/user-manual'
      fullPath: '/dashboard/user-manual'
      preLoaderRoute: typeof DashboardUserManualRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/system-docs': {
      id: '/dashboard/system-docs'
      path: '/system-docs'
      fullPath: '/dashboard/system-docs'
      preLoaderRoute: typeof DashboardSystemDocsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/system-config': {
      id: '/dashboard/system-config'
      path: '/system-config'
      fullPath: '/dashboard/system-config'
      preLoaderRoute: typeof DashboardSystemConfigRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/role-permissions': {
      id: '/dashboard/role-permissions'
      path: '/role-permissions'
      fullPath: '/dashboard/role-permissions'
      preLoaderRoute: typeof DashboardRolePermissionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/menu-management': {
      id: '/dashboard/menu-management'
      path: '/menu-management'
      fullPath: '/dashboard/menu-management'
      preLoaderRoute: typeof DashboardMenuManagementRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/lookups': {
      id: '/dashboard/lookups'
      path: '/lookups'
      fullPath: '/dashboard/lookups'
      preLoaderRoute: typeof DashboardLookupsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/issue-reports': {
      id: '/dashboard/issue-reports'
      path: '/issue-reports'
      fullPath: '/dashboard/issue-reports'
      preLoaderRoute: typeof DashboardIssueReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/feature-requests': {
      id: '/dashboard/feature-requests'
      path: '/feature-requests'
      fullPath: '/dashboard/feature-requests'
      preLoaderRoute: typeof DashboardFeatureRequestsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/error-logs': {
      id: '/dashboard/error-logs'
      path: '/error-logs'
      fullPath: '/dashboard/error-logs'
      preLoaderRoute: typeof DashboardErrorLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/eip': {
      id: '/dashboard/eip'
      path: '/eip'
      fullPath: '/dashboard/eip'
      preLoaderRoute: typeof DashboardEipRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/dev-todos': {
      id: '/dashboard/dev-todos'
      path: '/dev-todos'
      fullPath: '/dashboard/dev-todos'
      preLoaderRoute: typeof DashboardDevTodosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/dev-history': {
      id: '/dashboard/dev-history'
      path: '/dev-history'
      fullPath: '/dashboard/dev-history'
      preLoaderRoute: typeof DashboardDevHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/audit-logs': {
      id: '/dashboard/audit-logs'
      path: '/audit-logs'
      fullPath: '/dashboard/audit-logs'
      preLoaderRoute: typeof DashboardAuditLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/assistant-intent': {
      id: '/dashboard/assistant-intent'
      path: '/assistant-intent'
      fullPath: '/dashboard/assistant-intent'
      preLoaderRoute: typeof DashboardAssistantIntentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/activity-logs': {
      id: '/dashboard/activity-logs'
      path: '/activity-logs'
      fullPath: '/dashboard/activity-logs'
      preLoaderRoute: typeof DashboardActivityLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/eip/tasks': {
      id: '/dashboard/eip/tasks'
      path: '/tasks'
      fullPath: '/dashboard/eip/tasks'
      preLoaderRoute: typeof DashboardEipTasksRouteImport
      parentRoute: typeof DashboardEipRoute
    }
    '/dashboard/eip/reports': {
      id: '/dashboard/eip/reports'
      path: '/reports'
      fullPath: '/dashboard/eip/reports'
      preLoaderRoute: typeof DashboardEipReportsRouteImport
      parentRoute: typeof DashboardEipRoute
    }
    '/dashboard/eip/recurring': {
      id: '/dashboard/eip/recurring'
      path: '/recurring'
      fullPath: '/dashboard/eip/recurring'
      preLoaderRoute: typeof DashboardEipRecurringRouteImport
      parentRoute: typeof DashboardEipRoute
    }
    '/dashboard/eip/quick-reports': {
      id: '/dashboard/eip/quick-reports'
      path: '/quick-reports'
      fullPath: '/dashboard/eip/quick-reports'
      preLoaderRoute: typeof DashboardEipQuickReportsRouteImport
      parentRoute: typeof DashboardEipRoute
    }
    '/dashboard/eip/projects': {
      id: '/dashboard/eip/projects'
      path: '/projects'
      fullPath: '/dashboard/eip/projects'
      preLoaderRoute: typeof DashboardEipProjectsRouteImport
      parentRoute: typeof DashboardEipRoute
    }
    '/dashboard/eip/my-tasks': {
      id: '/dashboard/eip/my-tasks'
      path: '/my-tasks'
      fullPath: '/dashboard/eip/my-tasks'
      preLoaderRoute: typeof DashboardEipMyTasksRouteImport
      parentRoute: typeof DashboardEipRoute
    }
    '/dashboard/eip/members': {
      id: '/dashboard/eip/members'
      path: '/members'
      fullPath: '/dashboard/eip/members'
      preLoaderRoute: typeof DashboardEipMembersRouteImport
      parentRoute: typeof DashboardEipRoute
    }
    '/dashboard/eip/meetings': {
      id: '/dashboard/eip/meetings'
      path: '/meetings'
      fullPath: '/dashboard/eip/meetings'
      preLoaderRoute: typeof DashboardEipMeetingsRouteImport
      parentRoute: typeof DashboardEipRoute
    }
    '/dashboard/eip/feature-requests': {
      id: '/dashboard/eip/feature-requests'
      path: '/feature-requests'
      fullPath: '/dashboard/eip/feature-requests'
      preLoaderRoute: typeof DashboardEipFeatureRequestsRouteImport
      parentRoute: typeof DashboardEipRoute
    }
    '/dashboard/eip/documents': {
      id: '/dashboard/eip/documents'
      path: '/documents'
      fullPath: '/dashboard/eip/documents'
      preLoaderRoute: typeof DashboardEipDocumentsRouteImport
      parentRoute: typeof DashboardEipRoute
    }
    '/dashboard/eip/changelog': {
      id: '/dashboard/eip/changelog'
      path: '/changelog'
      fullPath: '/dashboard/eip/changelog'
      preLoaderRoute: typeof DashboardEipChangelogRouteImport
      parentRoute: typeof DashboardEipRoute
    }
    '/dashboard/eip/calendar': {
      id: '/dashboard/eip/calendar'
      path: '/calendar'
      fullPath: '/dashboard/eip/calendar'
      preLoaderRoute: typeof DashboardEipCalendarRouteImport
      parentRoute: typeof DashboardEipRoute
    }
    '/dashboard/eip/assistant': {
      id: '/dashboard/eip/assistant'
      path: '/assistant'
      fullPath: '/dashboard/eip/assistant'
      preLoaderRoute: typeof DashboardEipAssistantRouteImport
      parentRoute: typeof DashboardEipRoute
    }
    '/dashboard/eip/announcements': {
      id: '/dashboard/eip/announcements'
      path: '/announcements'
      fullPath: '/dashboard/eip/announcements'
      preLoaderRoute: typeof DashboardEipAnnouncementsRouteImport
      parentRoute: typeof DashboardEipRoute
    }
    '/dashboard/eip/projects/': {
      id: '/dashboard/eip/projects/'
      path: '/'
      fullPath: '/dashboard/eip/projects/'
      preLoaderRoute: typeof DashboardEipProjectsIndexRouteImport
      parentRoute: typeof DashboardEipProjectsRoute
    }
    '/dashboard/eip/meetings/': {
      id: '/dashboard/eip/meetings/'
      path: '/'
      fullPath: '/dashboard/eip/meetings/'
      preLoaderRoute: typeof DashboardEipMeetingsIndexRouteImport
      parentRoute: typeof DashboardEipMeetingsRoute
    }
    '/dashboard/eip/projects/$id': {
      id: '/dashboard/eip/projects/$id'
      path: '/$id'
      fullPath: '/dashboard/eip/projects/$id'
      preLoaderRoute: typeof DashboardEipProjectsIdRouteImport
      parentRoute: typeof DashboardEipProjectsRoute
    }
    '/dashboard/eip/meetings/$id': {
      id: '/dashboard/eip/meetings/$id'
      path: '/$id'
      fullPath: '/dashboard/eip/meetings/$id'
      preLoaderRoute: typeof DashboardEipMeetingsIdRouteImport
      parentRoute: typeof DashboardEipMeetingsRoute
    }
    '/dashboard/eip/feature-requests/new': {
      id: '/dashboard/eip/feature-requests/new'
      path: '/new'
      fullPath: '/dashboard/eip/feature-requests/new'
      preLoaderRoute: typeof DashboardEipFeatureRequestsNewRouteImport
      parentRoute: typeof DashboardEipFeatureRequestsRoute
    }
    '/dashboard/eip/feature-requests/$id': {
      id: '/dashboard/eip/feature-requests/$id'
      path: '/$id'
      fullPath: '/dashboard/eip/feature-requests/$id'
      preLoaderRoute: typeof DashboardEipFeatureRequestsIdRouteImport
      parentRoute: typeof DashboardEipFeatureRequestsRoute
    }
    '/dashboard/eip/feature-requests/$id/edit': {
      id: '/dashboard/eip/feature-requests/$id/edit'
      path: '/edit'
      fullPath: '/dashboard/eip/feature-requests/$id/edit'
      preLoaderRoute: typeof DashboardEipFeatureRequestsIdEditRouteImport
      parentRoute: typeof DashboardEipFeatureRequestsIdRoute
    }
  }
}

interface DashboardEipFeatureRequestsIdRouteChildren {
  DashboardEipFeatureRequestsIdEditRoute: typeof DashboardEipFeatureRequestsIdEditRoute
}

const DashboardEipFeatureRequestsIdRouteChildren: DashboardEipFeatureRequestsIdRouteChildren =
  {
    DashboardEipFeatureRequestsIdEditRoute:
      DashboardEipFeatureRequestsIdEditRoute,
  }

const DashboardEipFeatureRequestsIdRouteWithChildren =
  DashboardEipFeatureRequestsIdRoute._addFileChildren(
    DashboardEipFeatureRequestsIdRouteChildren,
  )

interface DashboardEipFeatureRequestsRouteChildren {
  DashboardEipFeatureRequestsIdRoute: typeof DashboardEipFeatureRequestsIdRouteWithChildren
  DashboardEipFeatureRequestsNewRoute: typeof DashboardEipFeatureRequestsNewRoute
}

const DashboardEipFeatureRequestsRouteChildren: DashboardEipFeatureRequestsRouteChildren =
  {
    DashboardEipFeatureRequestsIdRoute:
      DashboardEipFeatureRequestsIdRouteWithChildren,
    DashboardEipFeatureRequestsNewRoute: DashboardEipFeatureRequestsNewRoute,
  }

const DashboardEipFeatureRequestsRouteWithChildren =
  DashboardEipFeatureRequestsRoute._addFileChildren(
    DashboardEipFeatureRequestsRouteChildren,
  )

interface DashboardEipMeetingsRouteChildren {
  DashboardEipMeetingsIdRoute: typeof DashboardEipMeetingsIdRoute
  DashboardEipMeetingsIndexRoute: typeof DashboardEipMeetingsIndexRoute
}

const DashboardEipMeetingsRouteChildren: DashboardEipMeetingsRouteChildren = {
  DashboardEipMeetingsIdRoute: DashboardEipMeetingsIdRoute,
  DashboardEipMeetingsIndexRoute: DashboardEipMeetingsIndexRoute,
}

const DashboardEipMeetingsRouteWithChildren =
  DashboardEipMeetingsRoute._addFileChildren(DashboardEipMeetingsRouteChildren)

interface DashboardEipProjectsRouteChildren {
  DashboardEipProjectsIdRoute: typeof DashboardEipProjectsIdRoute
  DashboardEipProjectsIndexRoute: typeof DashboardEipProjectsIndexRoute
}

const DashboardEipProjectsRouteChildren: DashboardEipProjectsRouteChildren = {
  DashboardEipProjectsIdRoute: DashboardEipProjectsIdRoute,
  DashboardEipProjectsIndexRoute: DashboardEipProjectsIndexRoute,
}

const DashboardEipProjectsRouteWithChildren =
  DashboardEipProjectsRoute._addFileChildren(DashboardEipProjectsRouteChildren)

interface DashboardEipRouteChildren {
  DashboardEipAnnouncementsRoute: typeof DashboardEipAnnouncementsRoute
  DashboardEipAssistantRoute: typeof DashboardEipAssistantRoute
  DashboardEipCalendarRoute: typeof DashboardEipCalendarRoute
  DashboardEipChangelogRoute: typeof DashboardEipChangelogRoute
  DashboardEipDocumentsRoute: typeof DashboardEipDocumentsRoute
  DashboardEipFeatureRequestsRoute: typeof DashboardEipFeatureRequestsRouteWithChildren
  DashboardEipMeetingsRoute: typeof DashboardEipMeetingsRouteWithChildren
  DashboardEipMembersRoute: typeof DashboardEipMembersRoute
  DashboardEipMyTasksRoute: typeof DashboardEipMyTasksRoute
  DashboardEipProjectsRoute: typeof DashboardEipProjectsRouteWithChildren
  DashboardEipQuickReportsRoute: typeof DashboardEipQuickReportsRoute
  DashboardEipRecurringRoute: typeof DashboardEipRecurringRoute
  DashboardEipReportsRoute: typeof DashboardEipReportsRoute
  DashboardEipTasksRoute: typeof DashboardEipTasksRoute
}

const DashboardEipRouteChildren: DashboardEipRouteChildren = {
  DashboardEipAnnouncementsRoute: DashboardEipAnnouncementsRoute,
  DashboardEipAssistantRoute: DashboardEipAssistantRoute,
  DashboardEipCalendarRoute: DashboardEipCalendarRoute,
  DashboardEipChangelogRoute: DashboardEipChangelogRoute,
  DashboardEipDocumentsRoute: DashboardEipDocumentsRoute,
  DashboardEipFeatureRequestsRoute:
    DashboardEipFeatureRequestsRouteWithChildren,
  DashboardEipMeetingsRoute: DashboardEipMeetingsRouteWithChildren,
  DashboardEipMembersRoute: DashboardEipMembersRoute,
  DashboardEipMyTasksRoute: DashboardEipMyTasksRoute,
  DashboardEipProjectsRoute: DashboardEipProjectsRouteWithChildren,
  DashboardEipQuickReportsRoute: DashboardEipQuickReportsRoute,
  DashboardEipRecurringRoute: DashboardEipRecurringRoute,
  DashboardEipReportsRoute: DashboardEipReportsRoute,
  DashboardEipTasksRoute: DashboardEipTasksRoute,
}

const DashboardEipRouteWithChildren = DashboardEipRoute._addFileChildren(
  DashboardEipRouteChildren,
)

interface DashboardRouteChildren {
  DashboardActivityLogsRoute: typeof DashboardActivityLogsRoute
  DashboardAssistantIntentRoute: typeof DashboardAssistantIntentRoute
  DashboardAuditLogsRoute: typeof DashboardAuditLogsRoute
  DashboardDevHistoryRoute: typeof DashboardDevHistoryRoute
  DashboardDevTodosRoute: typeof DashboardDevTodosRoute
  DashboardEipRoute: typeof DashboardEipRouteWithChildren
  DashboardErrorLogsRoute: typeof DashboardErrorLogsRoute
  DashboardFeatureRequestsRoute: typeof DashboardFeatureRequestsRoute
  DashboardIssueReportsRoute: typeof DashboardIssueReportsRoute
  DashboardLookupsRoute: typeof DashboardLookupsRoute
  DashboardMenuManagementRoute: typeof DashboardMenuManagementRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardRolePermissionsRoute: typeof DashboardRolePermissionsRoute
  DashboardSystemConfigRoute: typeof DashboardSystemConfigRoute
  DashboardSystemDocsRoute: typeof DashboardSystemDocsRoute
  DashboardUserManualRoute: typeof DashboardUserManualRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardActivityLogsRoute: DashboardActivityLogsRoute,
  DashboardAssistantIntentRoute: DashboardAssistantIntentRoute,
  DashboardAuditLogsRoute: DashboardAuditLogsRoute,
  DashboardDevHistoryRoute: DashboardDevHistoryRoute,
  DashboardDevTodosRoute: DashboardDevTodosRoute,
  DashboardEipRoute: DashboardEipRouteWithChildren,
  DashboardErrorLogsRoute: DashboardErrorLogsRoute,
  DashboardFeatureRequestsRoute: DashboardFeatureRequestsRoute,
  DashboardIssueReportsRoute: DashboardIssueReportsRoute,
  DashboardLookupsRoute: DashboardLookupsRoute,
  DashboardMenuManagementRoute: DashboardMenuManagementRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardRolePermissionsRoute: DashboardRolePermissionsRoute,
  DashboardSystemConfigRoute: DashboardSystemConfigRoute,
  DashboardSystemDocsRoute: DashboardSystemDocsRoute,
  DashboardUserManualRoute: DashboardUserManualRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
